# Caesarian classification dataset

In [2]:
import pandas as pd
import numpy as np

# Perceptron Model 

In [3]:
#loading the data
data=pd.read_csv(r"C:\Users\dell\Downloads\caesarian.csv")

In [4]:
data.head()
col=data.columns.tolist()
col



Index(['id', ''Age'', ''Delivery', ''Delivery.1', ''Blood', ''Heart',
       'Caesarian'],
      dtype='object')


['id', "'Age'", "'Delivery", "'Delivery.1", "'Blood", "'Heart", 'Caesarian']

'Caesarian' is the Dependant(Output) Variable here.


In [5]:
Threshold=0                #Taking 0 as threshold value
w_bias=w_age=w_del_no=w_del_time=w_BP=w_Heart=0       #Initializing weights 
learning_rate=1
data.rename(columns={"'Age'":'age',"'Delivery":'Delivery no.',"'Delivery.1":'Delivery_Time',"'Blood":'B.o.P',"'Heart":'Heart_Problem'},inplace=True)
data.head()



id  age  Delivery no.  Delivery_Time  B.o.P  Heart_Problem  Caesarian
0   1   22             1              0      2              0          0
1   2   26             2              0      1              0          1
2   3   26             2              1      1              0          0
3   4   28             1              0      2              0          0
4   5   22             2              0      1              0          1

In [6]:
#Converting vaiables to lists
inp_age=data['age'].tolist()
inp_Delivery_no=data['Delivery no.'].tolist()
inp_Delivery_time=data['Delivery_Time'].tolist()
inp_B_o_P=data['B.o.P'].tolist()
inp_Heart_problem=data['Heart_Problem'].tolist()
target=data['Caesarian'].tolist()


In [7]:
print(inp_age)
print(target)

[22, 26, 26, 28, 22, 26, 27, 32, 28, 27, 36, 33, 23, 20, 29, 25, 25, 20, 37, 24, 26, 33, 25, 27, 20, 18, 18, 30, 32, 26, 25, 40, 32, 27, 26, 28, 33, 31, 31, 26, 27, 19, 36, 22, 36, 28, 26, 32, 26, 29, 33, 21, 30, 35, 29, 25, 32, 21, 26, 30, 22, 19, 32, 32, 31, 35, 28, 29, 25, 27, 17, 29, 28, 32, 38, 27, 33, 29, 25, 24]
[0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0]


In [8]:
for i in range(10):
    print("ITERATION:",i+1)
    k=0
    for j in range(len(inp_age)):
        print("Input Data",inp_age[i],inp_Delivery_no[i],inp_Delivery_time[i],inp_B_o_P[i],inp_Heart_problem[i],)
        if (w_bias+w_age*inp_age[i]+w_del_no*inp_Delivery_no[i]+w_del_time*inp_Delivery_time[i]+w_BP*inp_B_o_P[i]+w_Heart*inp_Heart_problem[i])>=Threshold:
            output=1
        else:
            output=0
        error=target[i]-output
        print("Error=",error)
        if error!=0:
            k=k+1
            w_bias=w_bias+learning_rate*1
            w_age=w_age+learning_rate*error*inp_age[i]
            w_del_no=w_del_no+learning_rate*error*inp_Delivery_no[i]
            w_del_time=w_del_time+learning_rate*error*inp_Delivery_time[i]
            
            w_BP=w_BP+learning_rate*error*inp_B_o_P[i]
            w_Heart=w_Heart+learning_rate*error*inp_Heart_problem[i]
            
            print("Updatd weights",w_bias,w_age,w_del_no,w_del_time,w_BP,w_Heart)
    if k==0:
        print("Model is successfully trained")
        print("Final weights=",w_bias,w_age,w_del_no,w_del_time,w_BP,w_Heart)
        break
    

ITERATION: 1
Input Data 22 1 0 2 0
Error= -1
Updatd weights 1 -22 -1 0 -2 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Error= 0
Input Data 22 1 0 2 0
Err

# SVM Model

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score



In [10]:
data2=data
data2.head()


id  age  Delivery no.  Delivery_Time  B.o.P  Heart_Problem  Caesarian
0   1   22             1              0      2              0          0
1   2   26             2              0      1              0          1
2   3   26             2              1      1              0          0
3   4   28             1              0      2              0          0
4   5   22             2              0      1              0          1

In [11]:
#shape of dataset
data2.shape

(80, 7)

In [12]:
#The input(Independent) variables
x=data[data.columns[1:6]]
print(x)
print(x.shape)

    age  Delivery no.  Delivery_Time  B.o.P  Heart_Problem
0    22             1              0      2              0
1    26             2              0      1              0
2    26             2              1      1              0
3    28             1              0      2              0
4    22             2              0      1              0
5    26             1              1      0              0
6    27             2              0      1              0
7    32             3              0      1              0
8    28             2              0      1              0
9    27             1              1      1              0
10   36             1              0      1              0
11   33             1              1      0              0
12   23             1              1      1              0
13   20             1              0      1              1
14   29             1              2      0              1
15   25             1              2      0             

In [13]:
#The output(Depenendant) variable
y=data[data.columns[6:7]]
print(y)
print(y.shape)

    Caesarian
0           0
1           1
2           0
3           0
4           1
5           0
6           0
7           1
8           0
9           1
10          0
11          1
12          0
13          0
14          1
15          0
16          0
17          1
18          1
19          1
20          0
21          1
22          0
23          1
24          1
25          0
26          1
27          0
28          1
29          0
..        ...
50          0
51          1
52          0
53          0
54          1
55          0
56          1
57          1
58          1
59          1
60          0
61          1
62          1
63          1
64          0
65          1
66          1
67          0
68          1
69          0
70          1
71          1
72          0
73          0
74          1
75          0
76          1
77          1
78          1
79          0

[80 rows x 1 columns]
(80, 1)


In [14]:
#Splitting test train data
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)
x_train.shape,x_test.shape

((64, 5), (16, 5))

In [15]:
#creating model with random weights and random hyperparameters
s1=SVC()

In [16]:
#Training s1 model
s1.fit(x_train,y_train)

H:\python setup\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
H:\python setup\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [17]:
obtained_output=s1.predict(x_test)

In [18]:
#checking accuracy of model on test data
accuracy_score(obtained_output,y_test)

0.625

In [19]:
#checking accuracy of model on train data
obt_out=s1.predict(x_train)
accuracy_score(obt_out,y_train)


0.8125

# SOM


In [20]:
data3=data.head()


In [21]:
data3

id  age  Delivery no.  Delivery_Time  B.o.P  Heart_Problem  Caesarian
0   1   22             1              0      2              0          0
1   2   26             2              0      1              0          1
2   3   26             2              1      1              0          0
3   4   28             1              0      2              0          0
4   5   22             2              0      1              0          1

In [22]:
#Training sample of data
X=np.array([[22,1,0,2,0],[26,2,0,1,0],[26,2,1,1,0],[28,1,0,2,0],[22,2,0,1,0]])
X

array([[22,  1,  0,  2,  0],
       [26,  2,  0,  1,  0],
       [26,  2,  1,  1,  0],
       [28,  1,  0,  2,  0],
       [22,  2,  0,  1,  0]])

In [23]:
target=np.array([0,1,0,0,1])

In [31]:
#Initializing weighgts      (dimentions of wts and data should be same)
w1=np.array([0.2,0.6,0.5,0.9,0.6])
w2=np.array([0.8,0.4,0.3,0.7,0.6])

In [25]:
lr=0.6

In [26]:
def Euclidean_distance(x,w):
    return np.sqrt(np.sum(x-w)**2)

In [28]:
#updation of wt when target==0
def update_weights1(x,w,lr):    
    return w+lr*(x-w)

In [29]:
#updation of wt when target!=0
def update_weights2(x,w,lr):
    return w-lr*(x-w)

In [33]:
#Training
for i in range(10):
    print("Iteration:",i+1)
    for j in range(5):          # 5 for total no of training samples
        print("Input ssmple:",X[j])
        print("Target:",target[j])
        d1=Euclidean_distance(X[j],w1)
        d2=Euclidean_distance(X[j],w2)
        if d1<=d2:
            print("Winner neuron is 1")
            #Now The weights corresponding to winner neuron will be updated
            if target[j]==0:
                w1=update_weights1(X[j],w1,lr)
            else:
                w1=update_weights2(X[j],w1,lr)

        else:
            print("Winner neuron is 2")
            w2=update_weights(X[j],w2,lr)
            if target[j]==0:
                w2=update_weights1(X[j],w1,lr)
            else:
                w2=update_weights2(X[j],w1,lr)

            
        #updated weights after 1st data sample
        print("Updated weights:",w1)
        print(w2)
        print()
        print()
        
    lr=lr*0.8
    print("Updated learning rate:",lr)
        
        
        
        
        

            

Iteration: 1
Input ssmple: [22  1  0  2  0]
Target: 0
Winner neuron is 1
Updated weights: [2.77133520e+01 4.14236088e-01 6.81656293e-01 2.58092946e+00
 1.93377896e-03]
[0.8 0.4 0.3 0.7 0.6]


Input ssmple: [26  2  0  1  0]
Target: 1
Winner neuron is 1
Updated weights: [2.78237338e+01 3.12074026e-01 7.25571665e-01 2.68278007e+00
 2.05836172e-03]
[0.8 0.4 0.3 0.7 0.6]


Input ssmple: [26  2  1  1  0]
Target: 0
Winner neuron is 1
Updated weights: [2.77062407e+01 4.20817829e-01 7.43251576e-01 2.57436779e+00
 1.92575278e-03]
[0.8 0.4 0.3 0.7 0.6]


Input ssmple: [28  1  0  2  0]
Target: 0
Winner neuron is 1
Updated weights: [2.77251660e+01 4.58131356e-01 6.95367958e-01 2.53736443e+00
 1.80168710e-03]
[0.8 0.4 0.3 0.7 0.6]


Input ssmple: [22  2  0  1  0]
Target: 1
Winner neuron is 1
Updated weights: [2.80940070e+01 3.58797225e-01 7.40166697e-01 2.63640838e+00
 1.91775990e-03]
[0.8 0.4 0.3 0.7 0.6]


Updated learning rate: 0.05153960755200004
Iteration: 2
Input ssmple: [22  1  0  2  0]
Targe